# Generated by Django 3.2 on 2022-07-13 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloseTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('radio1', models.CharField(blank=True, max_length=200, null=True)),
                ('radio2', models.CharField(blank=True, max_length=200, null=True)),
                ('radio3', models.CharField(blank=True, max_length=200, null=True)),
                ('radio4', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenEnd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenEnd_Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.openend')),
            ],
        ),
        migrations.AddField(
            model_name='openend',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
        migrations.CreateModel(
            name='CloseTest_Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.closetest')),
            ],
        ),
        migrations.AddField(
            model_name='closetest',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
    ]
